// <auto-generated />
namespace DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class model_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201906022011137_model_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
